version: "3"

services:
  frontend:
    networks:
      - my_network
    build: .
    ports:
      - 80:80

  backend:
    ports:
      - 5001:5001
    networks:
      - my_network
    build: ./server

networks:
  my_network:
